## REST, JSON and Text

### Class Objectives

* Understand what REST and JSON are, usage in python
* Review string parsing functionality and dummies in pandas (with merge, join, and concat)
* Reviewing some of the useful functionality in nltk
* Reviewing concepts of text handling (counting, stopwords, corpi and dictionaries)

### Data Goals

1. Given twitter data, we can build some understanding of what news to expect given a hashtag?

2. Is there any difference in sentiment across hashtags about the same topic?

3. What creative ways can we engineer features in order to predict a hashtag?

### REST and JSON

REST stands for Representational State Transfer. It's a simplification of architecture for networked applications. The basics found in Rails and Django apps insist on a RESTful framework for its ease of use compared to other architectures, such as CORBA, or SOAP.

RESTful applications do four primary things around "resources:"

* GET: retrieve the collection of data
* PUT: Replace or update the collection of data
* POST: Create a new collection of data
* DELETE: Delete the collection of data

It's also the premise for AJAX requests, and primarily how web services interact between your client (your computer) and the web server (where the web application resides). These AJAX calls primarily use JSON to send data between the server and client.

JSON stands for JavaScript Object Notation. For Python, it essentially looks like a stringified version of a dictionary:

In [1]:
valid_json = '{ "some_kinda_key": "some_kinda_value" }'

also_valid_json = '[{ "some_kinda_key": "some_kinda_value" }, { "some_other_key": "some_other_value" }]'

actually_a_dictionary = {'some_kinda_key': 'some_kinda_value'}

Since JSON uses a hash/dictionary-like format, it is traditionally unstructured, compared to CSV files, though when interacting with APIs (Application Programming Interface), if you're GETing a series of the same collection, generally, the data will look the same.

To load JSON into python, we use the json module. To find JSON, we'll dig it out of a network transfer from a website (petfinder will do, in this case).

In [2]:
import json

In [4]:
pets = json.load(open('petfinder.json'))

print type(pets)
print pets.keys()
print type(pets['results'])
print len(pets['results'])
print json.dumps(pets['meta_data'])
print type(json.dumps(pets))

<type 'dict'>
[u'meta_data', u'results', u'links']
<type 'list'>
15
{"total_results": 346182, "query": {"status": "Adoptable", "lon": "-73.9892", "page_size": "15", "page_number": "0", "location": "10003", "lat": "40.7316", "uri_prefix": "http://www.petfinder"}, "rows": 15, "page_number": 0, "query_id": "2A0BD832-546C-11E4-9E25-F1C9FFEE616C"}
<type 'str'>

In the above JSON, it looks like petfinder by default returns a list of 15 animals.

Petfinder also has an API, so you can get an API key and build requests using the requests package in python. You should get similar results.

In [6]:
import pandas as pd

In [7]:
petdf = pd.DataFrame(pets['results'])
petdf

,age,animal,contact_name,coords,country_code,date_updated,description,email_address,export,export_api,...,primary_breed,record_nav_links,region_code,secondary_breed,shelter_id,shelter_name,size,species,status,street_address
0,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-10-08T18:34:07Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Boxer,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,Staffordshire Bull Terrier,NY835,Social Tees Animal Rescue Foundation,Medium,Dog,Adoptable,please email dimitra.socialtees@gmail.com
1,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-08-20T20:56:44Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Manchester Terrier,{u'previous': u'http://www.petfinder/2A0BD832-...,NY,NaN,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
2,Adult,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-03-07T20:09:56Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Chihuahua,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,NaN,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
3,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-07-15T01:11:37Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Boston Terrier,{u'previous': u'http://www.petfinder/2A0BD832-...,NY,Chihuahua,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
4,Adult,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-10-13T13:14:10Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Shih Tzu,{u'previous': u'http://www.petfinder/2A0BD832-...,NY,Jack Russell Terrier,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
5,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-07-28T15:09:15Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Chihuahua,{u'previous': u'http://www.petfinder/2A0BD832-...,NY,Terrier,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
6,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-04-27T19:30:38Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Shih Tzu,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,NaN,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
7,Young,Cat,Samantha Brody,"40.7316,-73.9892",US,2014-06-06T13:59:06Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Tortoiseshell,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,NaN,NY835,Social Tees Animal Rescue Foundation,Medium,Cat,Adoptable,please email dimitra.socialtees@gmail.com
8,Adult,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-07-21T23:29:08Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Chihuahua,{u'previous': u'http://www.petfinder/2A0BD832-...,NY,Terrier,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
9,Young,Dog,Dimitra Bennett,"40.7316,-73.9892",US,2014-09-20T23:27:52Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,dimitra@socialteesnyc.org,True,True,...,Labrador Retriever,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,Husky,NY835,Social Tees Animal Rescue Foundation,Medium,Dog,Adoptable,please email dimitra.socialtees@gmail.com
10,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-09-09T16:09:07Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Black and Tan Coonhound,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,Hound,NY835,Social Tees Animal Rescue Foundation,Medium,Dog,Adoptable,please email dimitra.socialtees@gmail.com
11,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-09-15T15:27:49Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Catahoula Leopard Dog,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,Pit Bull Terrier,NY835,Social Tees Animal Rescue Foundation,Medium,Dog,Adoptable,please email dimitra.socialtees@gmail.com
12,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-09-16T15:32:26Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Shih Tzu,{u'previous': u'http://www.petfinder/2A0BD832-...,NY,NaN,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com
13,Baby,Dog,Dimitra Bennett,"40.7316,-73.9892",US,2014-10-12T04:56:18Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,dimitra@socialteesnyc.org,True,True,...,Weimaraner,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,NaN,NY835,Social Tees Animal Rescue Foundation,Medium,Dog,Adoptable,please email dimitra.socialtees@gmail.com
14,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-09-08T18:09:12Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Maltese,{u'next': u'http://www.petfinder/2A0BD832-546C...,NY,Poodle,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com

Pulling data from text
One technique for working with strings in pandas: pulling out strings. Imagine we wanted to create a feature called "is_terrier." Our steps would be to:

1. Use the two breed fields
2. Check if either field if the "terrier" text is included
3. Set a 1 if either field has "terrier" or a 0 if it does not.

Sample Code:

In [8]:
petdf['is_terrier'] = 0 # let's default to 0, so we only need to update as we recognize values
petdf.ix[petdf.primary_breed.str.contains('Terrier'), 'is_terrier'] = 1
petdf.ix[(petdf.secondary_breed.notnull()) & (petdf.secondary_breed.str.contains('Terrier')), 'is_terrier'] = 1

print petdf.groupby('is_terrier').age.count()

is_terrier
0    8
1    7
Name: age, dtype: int64

### Creating dummy variables
Another instance we'll commonly need to handle is converting categorical data into numerical data. While some domain languages (such as R) have built in ways to numerate categorical data, we'll need to depend on keeping everything numerical in python.

After creating a dummy matrix, we'll want to use a join to bridge the data back together. Note the variety of ways to join data together in pandas:

function - description

* append - functionality that works much like list.append(). imagine taking one data frame and appending it to another at the bottom (by rows)
* concat - this functionality would take a list of dataframes, where the first is the "primary", and all others are appended, like a queue.
* merge - link two data frames together, by merging columns together when the two columns defined to merge on are equal.
* join - runs very similarly to merge, but specifically uses the indexes. very common to use alongside get_dummies.

Below, we'll create a new data frame instance that "dummies" the size of the dog, and then attaches the sizes as new columns.

In [9]:
import numpy as np

# simple proof of concept on how concat works; otherwise, ignore
newdf = pd.concat([petdf[:7], petdf[7:]])
print newdf == petdf
# NaN is always false on equality (python gotcha!)
print
print 'numpy nan truth check!'
print np.nan == np.nan
print
sizes = pd.get_dummies(petdf['size'])
print sizes.head()

petdf_wsizes = petdf.join(sizes)
petdf_wsizes.head()

     age animal contact_name coords country_code date_updated description  \
0   True   True         True   True         True         True        True
1   True   True         True   True         True         True        True
2   True   True         True   True         True         True        True
3   True   True         True   True         True         True        True
4   True   True         True   True         True         True        True
5   True   True         True   True         True         True        True
6   True   True         True   True         True         True        True
7   True   True         True   True         True         True        True
8   True   True         True   True         True         True        True
9   True   True         True   True         True         True        True
10  True   True         True   True         True         True        True
11  True   True         True   True         True         True        True
12  True   True         True   True         True         True        True
13  True   True         True   True         True         True        True
14  True   True         True   True         True         True        True

   email_address export export_api    ...     record_nav_links region_code  \
0           True   True       True    ...                 True        True
1           True   True       True    ...                 True        True
2           True   True       True    ...                 True        True
3           True   True       True    ...                 True        True
4           True   True       True    ...                 True        True
5           True   True       True    ...                 True        True
6           True   True       True    ...                 True        True
7           True   True       True    ...                 True        True
8           True   True       True    ...                 True        True
9           True   True       True    ...                 True        True
10          True   True       True    ...                 True        True
11          True   True       True    ...                 True        True
12          True   True       True    ...                 True        True
13          True   True       True    ...                 True        True
14          True   True       True    ...                 True        True

   secondary_breed shelter_id shelter_name  size species status  \
0             True       True         True  True    True   True
1            False       True         True  True    True   True
2            False       True         True  True    True   True
3             True       True         True  True    True   True
4             True       True         True  True    True   True
5             True       True         True  True    True   True
6            False       True         True  True    True   True
7            False       True         True  True    True   True
8             True       True         True  True    True   True
9             True       True         True  True    True   True
10            True       True         True  True    True   True
11            True       True         True  True    True   True
12           False       True         True  True    True   True
13           False       True         True  True    True   True
14            True       True         True  True    True   True

   street_address is_terrier
0            True       True
1            True       True
2            True       True
3            True       True
4            True       True
5            True       True
6            True       True
7            True       True
8            True       True
9            True       True
10           True       True
11           True       True
12           True       True
13           True       True
14           True       True

[15 rows x 34 columns]

numpy nan truth check!
False

   Medium  Small
0     1.0    0.0
1     0.0    1.0
2     0.0    1.0
3     0.0    1.0
4     0.0    1.0

,age,animal,contact_name,coords,country_code,date_updated,description,email_address,export,export_api,...,secondary_breed,shelter_id,shelter_name,size,species,status,street_address,is_terrier,Medium,Small
0,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-10-08T18:34:07Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Staffordshire Bull Terrier,NY835,Social Tees Animal Rescue Foundation,Medium,Dog,Adoptable,please email dimitra.socialtees@gmail.com,1,1.0,0.0
1,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-08-20T20:56:44Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,NaN,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com,1,0.0,1.0
2,Adult,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-03-07T20:09:56Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,NaN,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com,0,0.0,1.0
3,Young,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-07-15T01:11:37Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Chihuahua,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com,1,0.0,1.0
4,Adult,Dog,Samantha Brody,"40.7316,-73.9892",US,2014-10-13T13:14:10Z,Please VISIT OUR FACEBOOK PAGE AND WEBSITE for...,samantha@socialteesnyc.org,True,True,...,Jack Russell Terrier,NY835,Social Tees Animal Rescue Foundation,Small,Dog,Adoptable,please email dimitra.socialtees@gmail.com,1,0.0,1.0

In [11]:
# coding=utf-8
from twitter import *
import twitterconfig as config

In [12]:
"""
there would be code here to set up a dictionary including everything required to load the authentication for twitter.
What are the advantages of setting up a dictionary here instead of just defining it below?
"""
t = Twitter(
    auth=OAuth(
        token=config.TOKEN,
        token_secret=config.TOKEN_SECRET,
        consumer_key=config.CONSUMER_KEY,
        consumer_secret=config.CONSUMER_SECRET)
    )

hashtags=[
    u'hongkong',
    u'occupycentral',
    u'umbrellarevolution',
    u'china',
    u'hk',
    u'admiralty',
    u'occupyhk',
]

all_results = []
for hashtag in hashtags:
    results = t.search.tweets(q='#'+hashtag, count=100, result_type='mixed')
    for r in results['statuses']:
        try:
            clean_tweet = unicode(r['text']).encode('utf-8').replace('\n', ' ').replace('\r', ' ').replace('"', "'")
            print u','.join([unicode(r['id']),'"'+clean_tweet+'"', '"'+hashtag+'"'])
        except UnicodeDecodeError:
            pass

724027359427473408,"Amazing stacked architecture of #HongKong shows housing of rather dense population.(Julia Wimmerlin via Mail Online) https://t.co/N3Tv5hfs5Z","hongkong"
724362388728762368,"#HR #Job alert: HR Operations Coordinator | Manulife | #HongKong https://t.co/KrW7wCZZxX #Jobs #Hiring","hongkong"
724361734312628224,"Check out the #HKTB for great family travel deals t Hong Kong - https://t.co/WRVNJDRCKn #HongKong #HongKongtravel","hongkong"
724361438710501377,"Interested in a #IT #job near #HongKong? This could be a great fit: https://t.co/UUwKsCovwS #CareersAtTU #LifeAtTU #Hiring","hongkong"
724361386747285505,"#anzacday2016 #anzacday in #hongkong amazing numbers attending #dawnservice https://t.co/qlSHzph7ej","hongkong"
724360996286922752,"3 days in #HongKong full of excitement, amazing food, hiking and amazing views..next stop Tokyo #ourcrazylives https://t.co/HmkRShKAXR","hongkong"
724360298614894597,"Moderate pollution (27) at 5AM. Low for #HongKong. Smile and go out for a ride :) https://t.co/7en0dPZpoN #airpollution","hongkong"
724359049962131456,"WHY #hongkong https://t.co/LYXjOELFRl","hongkong"
724358307411046401,"This #TinyApartment is jam packed with secret goodies https://t.co/gOVoYhcSfP via @nypost #HongKong #RealEstate","hongkong"
724356943037353984,"We're #hiring! Read about our latest #job opening here: Senior Solution Sales Consultant - https://t.co/IOwnXvdCMU #CareersAtTU #HongKong","hongkong"
724356877014949888,"#HongKong #Asia #video #pics  https://t.co/Z4zcgMaeKe","hongkong"
724356518490050561,"#HongKong #Asia #video #pics  https://t.co/zcwqEiCMI9","hongkong"
724355442357334016,"#exo #HongKong #LOSTPLANET #kai #jongin https://t.co/ZUtGlKdlfr","hongkong"
724354516028514305,"RT @Ann11353257: @Dior I love this Movie!!! Thank you very much #Dior #HongKong Mr Jin Akanishi is PERFECTION!!!!  I appreciate #DiorHomme","hongkong"
724352880971374592,"An early start in #HongKong. Lest We Forget #AnzacDay https://t.co/QvPOxMQgIv","hongkong"
724352536694665217,"World's busiest district!!  #mongkok  #HongKong  #hk @ Mongkok, Hong Kong https://t.co/6m8LiS6ag2","hongkong"
724352045663166465,"#IT #Job in #HongKong: Senior Manager, Application Security at Manulife https://t.co/z9zG17taRm #Jobs #Hiring","hongkong"
724271558978465792,"'@Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME https://t.co/RGJiHEm6zw https://t.co/LykbE3eLYU'a.","occupycentral"
724228411850391553,"RT @Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME http://t.co/8vDxT3eliP http://t.co/FSJRVvzYQ5","occupycentral"
724044148160913409,"RT @Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME http://t.co/8vDxT3eliP http://t.co/FSJRVvzYQ5","occupycentral"
723952561691176960,"RT @Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME http://t.co/8vDxT3eliP http://t.co/FSJRVvzYQ5","occupycentral"
723942828741636096,"RT @Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME http://t.co/8vDxT3eliP http://t.co/FSJRVvzYQ5","occupycentral"
723802134601433088,"RT @Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME http://t.co/8vDxT3eliP http://t.co/FSJRVvzYQ5","occupycentral"
723703237866479617,"RT @Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME http://t.co/8vDxT3eliP http://t.co/FSJRVvzYQ5","occupycentral"
723542116610236416,"RT @Iyengarish: Best sign I've seen all day. @OCLPHK @HKFS1958 #OccupyCentral @TIME http://t.co/8vDxT3eliP http://t.co/FSJRVvzYQ5","occupycentral"
724356000665481221,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 05:55, noon 12:21, sunset 18:48 HKT (UTC+8), April 25. Day length: 12h 52m.","umbrellarevolution"
724254843120943104,"#umbrellarevolution #fragrantharbour #hongkong @ Hong Kong https://t.co/X9JNWhdTUH","umbrellarevolution"
723993949824794624,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 05:56, noon 12:22, sunset 18:47 HKT (UTC+8), April 24. Day length: 12h 51m.","umbrellarevolution"
723810209857191936,"#umbrellarevolution by jansebraten https://t.co/txsJ3k9uvB","umbrellarevolution"
723646275661533188,".@joshuawongcf of @demosisto speaking to hong kong #umbrellarevolution. 'time is on our side. determine our future' https://t.co/zU15Dcgm72","umbrellarevolution"
723631841933180928,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 05:57, noon 12:22, sunset 18:47 HKT (UTC+8), April 23. Day length: 12h 50m.","umbrellarevolution"
723269615275544576,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 05:58, noon 12:22, sunset 18:47 HKT (UTC+8), April 22. Day length: 12h 49m.","umbrellarevolution"
723237101458714624,"Nathan Law on campus taking about Hong Kong politics #UmbrellaRevolution @AARCivist https://t.co/LwfQkUvYtZ","umbrellarevolution"
723210834416001024,"#art #instagramanet Render testing #keyshot #3d #zbrush #sculptures #3dprint #umbrella  #umbrellarevolution #hongkong #render #textur...","umbrellarevolution"
723169475512537089,"This smart umbrella tells you when it's going to rain https://t.co/KWKJyTf3no @the_oombrella #UmbrellaRevolution #smartTechnology","umbrellarevolution"
723139009220734976,"#UmbrellaRevolution, #Singapore Style","umbrellarevolution"
722907533338222594,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 05:59, noon 12:22, sunset 18:46 HKT (UTC+8), April 21. Day length: 12h 48m.","umbrellarevolution"
722896882511384578,"@Cvetin  VMRO can used #UmbrellaRevolution vs SDSM #ColorfulRevolution Police can use Paintball Gear https://t.co/7MVVbC10vF","umbrellarevolution"
722703670996004864,"#hk928umbrella #UmbrellaRevolution Looking for people willing to participate in interviews about SoMe and #UmbrellaMovement! Get in touch!","umbrellarevolution"
722629702322491392,"@EdebiriSolomon Promises infrastructural development #UmbrellaRevolution #EdoDecides cc @SKSolaKuti @segalink https://t.co/iknoYBXJMw","umbrellarevolution"
722628027377537024,"@Iduoriyekemwen For a Greater Edo #UmbrellaRevolution #EdoDecides cc @hitmankunlecole @pdpsouthsouth @ndefiii https://t.co/JHWApxKV0F","umbrellarevolution"
722627259014590464,"#EdoDecides #TheFutureisNow #UmbrellaRevolution cc @P_Nigeria @segalink @Marvinog @vaskis @Osekita @gbemy01 @gbemy01 https://t.co/3xkQqmFCbI","umbrellarevolution"
722600725591625730,"When you need #TheTVirus and #antivirus #umbrellacorporation #umbrellarevolution #residentevil #biohazard https://t.co/ZJwjHeVcms","umbrellarevolution"
722545112723693568,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 05:59, noon 12:22, sunset 18:46 HKT (UTC+8), April 20. Day length: 12h 47m.","umbrellarevolution"
722256599549624320,"Joshua Wong @ Harvard, 21 April,2016, two events lined up for the day.  #UmbrellaRevolution #JoshuaWong... https://t.co/Mms82QDZ17","umbrellarevolution"
722249252949209088,"RT @DimiSevastopulo: #UmbrellaRevolution https://t.co/ARClh7OaC2 https://t.co/ZspBauflrl","umbrellarevolution"
722248196479651840,"RT @DimiSevastopulo: #UmbrellaRevolution https://t.co/ARClh7OaC2 https://t.co/ZspBauflrl","umbrellarevolution"
722247146683174912,"RT @Broquerefr: We'll be back #UmbrellaRevolution https://t.co/jtarpgwpWS","umbrellarevolution"
722235942774448128,"RT @Broquerefr: We'll be back #UmbrellaRevolution https://t.co/jtarpgwpWS","umbrellarevolution"
722235311187697665,"RT @Broquerefr: We'll be back #UmbrellaRevolution https://t.co/jtarpgwpWS","umbrellarevolution"
722183025589690368,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 06:00, noon 12:23, sunset 18:45 HKT (UTC+8), April 19. Day length: 12h 45m.","umbrellarevolution"
722101478186422273,"It's the time to determine the future of #HongKong, the future of my city - Joshua Wong #UmbrellaRevolution https://t.co/OZYbWZuTGY","umbrellarevolution"
721866970656690177,"#Solidarity: TNC &amp; @Demosisto. Our representatives welcome #JoshuaWong to NY. @joshuawongcf #UmbrellaRevolution https://t.co/Ofiu3K8qds","umbrellarevolution"
721820834130759681,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 06:01, noon 12:23, sunset 18:45 HKT (UTC+8), April 18. Day length: 12h 44m.","umbrellarevolution"
721458680940662785,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 06:02, noon 12:23, sunset 18:45 HKT (UTC+8), April 17. Day length: 12h 43m.","umbrellarevolution"
721130619032485888,"Moved on up to #Maine for the weekend and we have an #umbrellarevolution #wickedweird https://t.co/K1EfqQzTYK","umbrellarevolution"
721096538248843264,"Good morning, #UmbrellaRevolution #OccupyHK! :) #Sunrise 06:03, noon 12:23, sunset 18:44 HKT (UTC+8), April 16. Day length: 12h 42m.","umbrellarevolution"
724229059396419584,"#China's first female astronaut says women have advantages in working in space https://t.co/61GFwvsbsg https://t.co/jxG3mPLK9W","china"
724055347435065344,"#China has world's largest number of personnel involved in science and tech: 81.14 million by end of 2014. https://t.co/txMd9vZ4nF","china"
724364179621208064,"Environmental time bomb! #China is building floating nuclear power stations https://t.co/nTDi1woatJ #Fukushima","china"
724364144607023104,"#China search giant Baidu building self driving hub in silicon valley https://t.co/DIDuVgre14 #AI #cars #telematics","china"
724363822283239424,"#CYPUNK A #NIGHT in #CHINA #LOTLITA #ART by #BEATSOFHELL https://t.co/h8nR4cuvgf","china"
724363821645619201,"#noticias #economia #China lanza una ofensiva para fijar el precio del #oro https://t.co/mOj0Nwl7so https://t.co/Ffjn83TYDp","china"
724363815673016320,"#CYPUNK A #NIGHT in #CHINA #LOTLITA #ART by #BEATSOFHELL https://t.co/ZK66T9xVOQ","china"
724363808710483969,"#CYPUNK A #NIGHT in #CHINA #LOTLITA #ART by #BEATSOFHELL https://t.co/RoB3GibSLo","china"
724363753047740416,"RT @AmityShlaes: Soros sounds correct here. #China https://t.co/d6Oi3Kx5hM","china"
724363618444144641,"#Rusia y #China unen esfuerzos para conquistar otros planetas #Cuba https://t.co/25n4OzAwQ4","china"
724363470473420801,"19% of US #nationaldebt is owed to the Social Security trust. 2.7 trillion.  11% owed to the #FederalReserve .  8% to #China. 6% to Japan","china"
724363292601376768,"RT @anupamifs: #yoga #India #China common Asian #culture and philosophical heritage  https://t.co/V55JACFTqy","china"
724363106164596736,"RT @IronMaiden: Eddie is watching you Beijing. #IronMaiden #TheBookOfSoulsWorldTour #China #Beijing #Eddie https://t.co/VbB2cDMRa2","china"
724363045762437120,"Don't have a degree? How about a TEFL internship in China? https://t.co/yI4oeUBJml #china #TEFL #teachenglish #esl https://t.co/twRsdSzc98","china"
724362772650172416,"NTHU addresses student protesters against school merging with NHCUE https://t.co/NVBkPBYPAp #china","china"
724362611563761664,"RT @PDChina: Woman spotted walking her pet, a blue #peacock in downtown #Wuhan, central #China's #Hubei province. https://t.co/KTXpW4LLfO","china"
724362527597981697,"RT @PDChina: Woman spotted walking her pet, a blue #peacock in downtown #Wuhan, central #China's #Hubei province. https://t.co/KTXpW4LLfO","china"
724362313290125312,"RT @PDChina: Woman spotted walking her pet, a blue #peacock in downtown #Wuhan, central #China's #Hubei province. https://t.co/KTXpW4LLfO","china"
724362159862460416,"#China proposes to build world's 2nd longest high-speed rail line in #India, vice general engineer of the CRC said. https://t.co/nAezLQtuP6","china"
724361876625342467,"Soros: #China's Debt-Fueled Growth Echoes US in 2007-08 https://t.co/UpbMY0rMKD #economy #health #healthy #high #loss","china"
724361790944063488,"Why #China #Censors Muzzled an #Internet Sensation: Adam Minter https://t.co/diA6FQ1K2i via @NewsRepublic","china"
724361767271436288,"RT @istalkpandas: romantic date @ipandacom #chengdupandabase #chengdu #china #pandacam #panda #pandas https://t.co/dFIbBEkinB","china"
724361675642687488,"Nothing like a night on the Bund with good friends. #Thankful #China by jacksonwellsmusic https://t.co/lYOKYwXYiR","china"
724361649230999552,"While America Debates the $20 Bill, China Moves Closer to Gold https://t.co/Egb5XLK7iM via @realalexjones #China #Gold #Silver","china"
724361479303094277,"RT @AQpk: #SabeenMahmud Assassination Linked To #Gwadar, #China Corridor #CPEC  https://t.co/xEHOiVyAYx","china"
724361320355774464,"Shanghai market place - #China #shanghai #marketplace #shopping by d_thirug https://t.co/sXoKYMP3GY","china"
724361316303953922,"Redgate Today Open Studio, good crowd!! #davidgumbs #davidoffarts #redgateresidency #beijing #china https://t.co/4aYUtioLfk","china"
724361311707078656,"#shanghai #china by off_for_miles https://t.co/wbxqVI1OOe","china"
724102630729900032,"#HK takes on #GothamCity. Champagne breakfast view from @UpperHouse_HKG https://t.co/8Re21Poxo7","hk"
722703050192855040,"Win a trip to #HK along with Michelin-dining, top attractions &amp; 5 star accommodation! Enter: https://t.co/KdNLWVDBYe https://t.co/NFuPKv4tQC","hk"
724357579275702272,"Hey handsome  bestbarber #signage #nofilter #sunny #hellsea #hk #barber #hesgotlegs https://t.co/HVDK7vkjrU","hk"
724355206868250624,"Perhaps, a voice of sanity in the #HK #independence debate (as opposed to the Red Queen's diktats)  https://t.co/WQH6Iw8gVz via @SCMP_News","hk"
724354801530626048,"Stand de @#MEETrade y @CCEJJ dentro del #PremioAdolfHorn gracias a #PanelStore #MisionComercial a #China y #HK https://t.co/ZkEcEAtTMn","hk"
724352815695564800,"RT @HinakhanDiehear: Hina Khan unseen pic with fan  #HK @ipriya0987 https://t.co/SOjfbCmQC6","hk"
724352536694665217,"World's busiest district!!  #mongkok  #HongKong  #hk @ Mongkok, Hong Kong https://t.co/6m8LiS6ag2","hk"
724351380950003712,"Heading to the Big Buddah on the top of a mountain!!  #hk  #bigbuddah  #gondola @ Big Buddah! https://t.co/FXv5FoJgQS","hk"
724346262313562112,"#HongKong #HK Use us to tap China market: Hong Kong to India Inc","hk"
724344050736848896,"The World is My Playground #ChinaDolls #HK #Trippin @ Hard Rock Cafe Hong Kong https://t.co/91TanUTGF6","hk"
724343456538103811,"Check out # 1 source for CA Magazine rebuild kits #AK47 #AR15 #glock #HK We test everything we sell! https://t.co/OaBOY43ulH","hk"
724343243370950656,"Werther Dominates International Field In Hong Kong's QEII Cup - Paulick Report https://t.co/ynJqKSGDEO #HK","hk"
724343242540519425,"Dior Homme Shows in Hong Kong - WWD https://t.co/fiukwsDxrH #HK","hk"
724343194100621316,"#SanMiguel #hk #hkstreetfood #HongKong #streetphotography #ricohgr #streetinternational #thepurephoto #noedit #bnw https://t.co/hdxAYdzJqE","hk"
724342828592062464,"#viet #thai Magic Power are apparently on the rocks https://t.co/EM5HGLzY4K #China #taiwan #hk","hk"
724340029598760960,"Peaceful calls for Hong Kong independence are protected by Bill of Rights, ex-top prosecutor says - South ... https://t.co/HlaF5vVc9i #hk","hk"
724334789113819137,"#hk #starferry #wanchaiferry #2016april by seanhongcorea https://t.co/s405pG3AtC","hk"
724327317623939080,"5 Persuasive Reasons to Love Hong Kong as an #Expat https://t.co/YrnFslIc2Q #hongkong #hk #china #travel #ttot","hk"
724321811312185344,"#HongKong #HK Hong Kong: Werther much the best in Queen Elizabeth II Cup","hk"
724315213714063361,"#hk  https://t.co/cnuPmzuTUx","hk"
724304471992340480,"Peaceful calls for Hong Kong independence are protected by Bill of Rights, ex-top prosecutor says - South ... https://t.co/WAXvvXzGUf #HK","hk"
724304469635174400,"Hong Kong Christians march on mainland liaison office to protest religious oppression - South China Morning Post https://t.co/xV7tlaH8uu #HK","hk"
724304468016160768,"Mainland women still flouting Hong Kong birth ban - South China Morning Post https://t.co/aeYJ3Yi3xq #HK","hk"
724304466430689280,"Hong Kong's Democratic Party opts for young guns as it puts forward seven candidates for Legco polls - Sou... https://t.co/rkP6Q8HQNj #HK","hk"
724298473323945985,"Hong Kong Christians march on mainland liaison office to protest religious oppression - South China Morning Post https://t.co/j9qzLq9vyR #hk","hk"
724298472665423872,"Mainland women still flouting Hong Kong birth ban - South China Morning Post https://t.co/D1jk6gv7pB #hk","hk"
724298471902040064,"International knowledge and standards keys for HK to move forward, HSBC head says - South China Morning Post https://t.co/r3wk3Aq1Si #hk","hk"
724298471100960769,"Hong Kong Polytechnic University move to set up two offshore firms 'contravened guidelines of institution ... https://t.co/G0lLB3KrYv #hk","hk"
724286843810803713,"RT @CRWilliams00: Fun at the range.  Real #gunsense #2A #Shooting #HK #Kimber https://t.co/zMCtzPNPOh","hk"
724285590934532097,"Fun at the range.  Real #gunsense #2A #Shooting #HK #Kimber https://t.co/zMCtzPNPOh","hk"
724282670386151424,"#hongkong #visithongkong #hk #hk2016 @ Hong Kong https://t.co/xJqTMB5edG","hk"
724282210807742464,"#HongKong #HK Hong Kong Christians march on mainland liaison office to protest religious oppression","hk"
724280206974918657,"#hongkong #visithongkong #hk #hk2016 @ Kowloon Bay, Hong Kong https://t.co/SbElDOJdIs","hk"
724279749741285378,"With my nephew #hongkong #oceanparkhongkong #hk #visithongkong #hk2016 @ OceanPark . HK https://t.co/dlRcdNG6Sz","hk"
724278988105900037,"For drinks or dinner, Yardbird is a great hangout! https://t.co/zZ1dFyqf1L #HK https://t.co/b5uHjF5qnR","hk"
724278516775268352,"Paintings and more at #PingPong in HK https://t.co/xH0DKfMrgF (My take on the 70s #HK art via @Forbes #That70sShow #Retro #Art","hk"
724278255273009152,"Sailing,, Victoria harbour #victoriaharbour #hongkong #hk #visithongkong #hk2016 https://t.co/FXcgkSPNoH","hk"
724277466999697408,"RT @Lisaraniray: #HK takes on #GothamCity. Champagne breakfast view from @UpperHouse_HKG https://t.co/8Re21Poxo7","hk"
724277316482785280,"RT @HinakhanDiehear: Hina Khan unseen pic with fan  #HK @ipriya0987 https://t.co/SOjfbCmQC6","hk"
724274963436449793,"#hongkong #noahark #hk #visithongkong # @ Noah's Ark https://t.co/6WLNJddXWE","hk"
724273220283731968,"#hongkong #visithongkong #hk2016 #hk @ Hongkong Island https://t.co/2gUGWIAS4g","hk"
724272638772785152,"Studio wid @hoodkingz_uk #HK","hk"
724337244908171265,"Schooner Yuniy Baltiets wintering. The Lieutenant Schmidt Embankment. Saint-Petersburg, Russia https://t.co/9RsUmHc6hN #admiralty #and #area","admiralty"
724308854465417216,"@Johnny_Cirucci @Watcher_Radio Vatican courts #Admiralty&gt;1666=legal https://t.co/pyvjMf4eJq https://t.co/odSQTtEeCw https://t.co/mQ8SzdOTCk","admiralty"
723855800528039936,"@gavthebrexit @Reptoid_Hunter @Magnacartman Vatican courts #Admiralty legal law=#MartialLaw https://t.co/pyvjMf4eJq https://t.co/0YyuGRkcfO","admiralty"
723761991110651904,"RT @Hwt123: @trutherbotbrwn @suzettepetillo 1666 man declared dead,lost at SEA&gt;#Admiralty https://t.co/pyvjMf4eJq https://t.co/pBPUduGIPk","admiralty"
723717729711058944,"@trutherbotbrwn @suzettepetillo 1666 man declared dead,lost at SEA&gt;#Admiralty https://t.co/pyvjMf4eJq https://t.co/pBPUduGIPk","admiralty"
723538234542854145,"@PhelpsDunbar welcomes 4 new associates https://t.co/BL8x8FhiCv #LaborAndEmployment #Business #Litigation #Admiralty https://t.co/nCFT0I8xAa","admiralty"
723368269579612160,"@Fingersflying Courts #Admiralty&gt;#LawoftheSEA&gt;#MartialLaw=legal law https://t.co/vH44lwYKuu https://t.co/lVPRFHGE9h https://t.co/1kMTpLniIU","admiralty"
723306843498377216,"Jessica Schalkowski is an #Admiralty Island National Monument special uses permit administrator. #Tongass https://t.co/F7LSYBvj5q","admiralty"
723170513728589824,"@GOPTechWeek Courts #fake&gt;#Admiralty&gt;#LawoftheSEA&gt;#MartialLaw=legal #CommonLaw&gt;#LawoftheLAND https://t.co/0MqvuMlL21 https://t.co/Sf7E4O0Urx","admiralty"
723157263616081922,"Courts #Admiralty&gt;#LawoftheSEA=legal law Common Law&gt;#LawoftheLAND https://t.co/0MqvuMlL21 https://t.co/u9nwQYhw3A","admiralty"

### Working with text and using NLTK

nltk stands for natural language toolkit. It's primary purpose in our data science toolkit sits around the following functionality:

* parsing text objects into lists of tokens
* providing context and similarity between text
* containers for large amounts of text (various texts from project gutenberg are included for download)
* tagging words
* building predictive models using text

Below we'll load in some previously generated twitter data into a pandas dataframe, though with some integration, it wouldn't be a stretch to stream them directly into a pandas data frame, or into a SQL database, which we could later pull in with pandas.

In [13]:
import pandas as pd

tweets = pd.read_csv('twitter5.csv')
tweets = tweets

print tweets

                      id                                              tweet  \
0     522205943074160640  Is this #HongKong 's Rodney King? Police need ...
1     521669229188501504  'We won't move and I'm ready to get arrested',...
2     522228472786067456  RT @stanyee: Footage of beating prompts #HongK...
3     522228386002108418  What is happening in Hong Kong is something th...
4     522228373964480512  #Funding:#HongKong #travel #startup @KlookTrav...
5     522228351231344640  HK police use pepper spray on protesters, beat...
6     522228250450206720  RT @stanyee: Footage of beating prompts #HongK...
7     522228232330817536  RT @stanyee: Footage of beating prompts #HongK...
8     522228119952822272  Squeezed. #vscocam #vsco_hub #vscogang #vscogr...
9     522228020069679104  RT @stanyee: Footage of beating prompts #HongK...
10    522227916659105792  BREAKING: #HongKong security chief says 6 poli...
11    522227892198334464  Trendingnews: #hongkong #demonstranten | #aang...
12    522227878755184642  @BBCBreaking In #HongKong #UmbrellaMovement, p...
13    522227788095303680  @cnnbrk In #HongKong #UmbrellaMovement, police...
14    522227771502653440  Map of the underpass in #hongkong where police...
15    522227564555673601  @nytimes In #HongKong #UmbrellaMovement, polic...
16    522227525598994432  RT @CoconutsHK: 37 men and 8 women arrested la...
17    522227458012368897             #Hongkong today http://t.co/QWD1odyMdS
18    522227399069802496  RT @SauloCorona: ICYMI: #HongKong tensions ris...
19    522227204743524353  RT @stanyee: Footage of beating prompts #HongK...
20    522227036161839105  Los 7 goles que le hicimos a #HongKong son los...
21    522227008042840064  #EXO #hongkong #FROMLOSTPLANET  #20140601 #cha...
22    522227000887361536  @WSJAsia @WSJ This was how the #HongKong polic...
23    522226702475218944  Statement by #HongKong Police about the video ...
24    522226690244628482  #hongkong Oil prices rebound... but not for lo...
25    522226686138388480  #hongkong Oil prices rebound... but not for lo...
26    522226684573933568  #hongkong Oil prices rebound... but not for lo...
27    522226680367034369  #HongKong RT @george_chen: First tear gas, no ...
28    522226675892092928  Footage of beating prompts #HongKong police to...
29    522226672771530754  the underpass in #hongkong where police used p...
...                  ...                                                ...
1466  522495130905763841  RT @krislc: Legislator Leung Kwok-hung aka Lon...
1467  522495102971699200  RT @krislc: Audrey Eu giving out free eggtarts...
1468  522494858507071488  RT @tomgrundy: Big Pictures from @TheAtlantic ...
1469  522494785152512000  RT @krislc: Mong Kok. 100 people. but seems ba...
1470  522494728147726337  RT @krislc: earlier: the 1 dollar coins that c...
1471  522494722938388480  RT @desiree_fa: 8 Police vans roll out from wa...
1472  522494481552011264  Mong Kok. 100 people. but seems barricades cou...
1473  522493948908941312  Sign the petition: Stand in solidarity with pr...
1474  522493690120388608  RT @krislc: Banner now #OccupyHK http://t.co/u...
1475  522493482980896768  RT @krislc: .@klustout here #OccupyHK http://t...
1476  522493408976596993  RT @cpjasia: Five HK Press Unions United in Co...
1477  522493263543300096  RT @krislc: 9:11pm. Rodney Street packed #Occu...
1478  522493200016359424  RT @krislc: packed around the stage; but loose...
1479  522493095821074432   RT @krislc: now #OccupyHK http://t.co/RJ3eedsXUY
1480  522492944020807680  RT @AgnesBun: Meanwhile in Sheung Wan... #Occu...
1481  522492841759875072  RT @krislc: This is the post. started 10:30am....
1482  522492750152077312  RT @HKFS1958: Urgently need face masks, saline...
1483  522492727682809856  RT @tomgrundy: Barriers being reinforced in tu...
1484  522492628680839168  RT @krislc: occupied area stretches from legis...
1485  522492375919120384  police can't stand the verbal abuse from prote...
1486  522492265512845312  RT @krislc: barricades also building up westbo...
1487  522492212412571649  Album of close up shots of the pepper spraying...
1488  522492047266443264  RT @krislc: calling wooden plates here to stre...
1489  522492008359665665  Sign the petition: Stand in solidarity with pr...
1490  522492004996239361  RT @krislc: Lung Wo Rd. What? source: https://...
1491  522491590443806720  RT @tomgrundy: Big Pictures from @TheAtlantic ...
1492  522491470146969600  RT @krislc: now &amp; signing off. #OccupyHK h...
1493  522491449322258434  RT @krislc: this amount of people will stay at...
1494  522490688298967040  Sign the petition: Stand in solidarity with pr...
1495  522490643483217920  RT @fion_li: Hong Kong Police Battle Protester...

       hashtag
0     hongkong
1     hongkong
2     hongkong
3     hongkong
4     hongkong
5     hongkong
6     hongkong
7     hongkong
8     hongkong
9     hongkong
10    hongkong
11    hongkong
12    hongkong
13    hongkong
14    hongkong
15    hongkong
16    hongkong
17    hongkong
18    hongkong
19    hongkong
20    hongkong
21    hongkong
22    hongkong
23    hongkong
24    hongkong
25    hongkong
26    hongkong
27    hongkong
28    hongkong
29    hongkong
...        ...
1466  occupyhk
1467  occupyhk
1468  occupyhk
1469  occupyhk
1470  occupyhk
1471  occupyhk
1472  occupyhk
1473  occupyhk
1474  occupyhk
1475  occupyhk
1476  occupyhk
1477  occupyhk
1478  occupyhk
1479  occupyhk
1480  occupyhk
1481  occupyhk
1482  occupyhk
1483  occupyhk
1484  occupyhk
1485  occupyhk
1486  occupyhk
1487  occupyhk
1488  occupyhk
1489  occupyhk
1490  occupyhk
1491  occupyhk
1492  occupyhk
1493  occupyhk
1494  occupyhk
1495  occupyhk

[1496 rows x 3 columns]

### Finding uniqueness of tweets

One important thing to do would be to find the uniqueness of a dataset. Here, we should measure uniqueness as number of unique tweets / number of tweets in the data set.

In [29]:
def tweet_uniqueness(series):
    return float(len(series.unique()))/len(series)
    #return (len(series.unique()) / len(series)) * 100

# shows that with the code above, we didn't get completely unique tweets.
print(tweet_uniqueness(tweets.id))

# code to drop duplicates based on the id column alone.
unique_tweets = tweets.drop_duplicates(subset=['id'])

print len(unique_tweets)
print tweet_uniqueness(unique_tweets.id)
print tweet_uniqueness(unique_tweets.tweet)

0.761363636364
1139
1.0
0.779631255487

In [30]:
for i in unique_tweets.hashtag.unique():
    print i, tweet_uniqueness(unique_tweets[unique_tweets.hashtag == i].tweet)

hongkong 0.863636363636
occupycentral 0.719047619048
umbrellarevolution 0.630872483221
china 0.950980392157
hk 0.970588235294
admiralty 0.716981132075
occupyhk 0.610778443114

Next we'll use nltk to tokenize the tweets. Tokens are really just units of words within parsed text.

To prep nltk and many of its functionalities, we'll need to download additional parts:

In [32]:
import nltk

def tokenize_tweet(t, remove_stop=True, remove_hashtag=False):
    import string
    import re
    tweet = t
    tweet = tweet.lower()
    tweet = re.sub('@\w+', 'TWITTER_HANDLE', tweet)
    tweet = re.sub('(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?', 'URL', tweet)
    tweet = tweet.translate(string.maketrans("",""), string.punctuation)
    words = nltk.tokenize.wordpunct_tokenize(tweet)
    if remove_stop:
        # How do we filter for words in the stopwords corpus?
        stopwords_filter = set(nltk.corpus.stopwords.words('english'))
        words = [word for word in words if word not in stopwords_filter]
    if remove_hashtag:
        # How do we filter out the actual hashtag in the tweet itself?
        words = [word for word in words if word[0] != '#']
    return words


unique_tweets['tokens'] = unique_tweets.tweet.apply(tokenize_tweet, remove_stop=True)
unique_tweets['tokens_w_stopwords'] = unique_tweets.tweet.apply(tokenize_tweet, remove_stop=False)

print unique_tweets['tokens_w_stopwords']

c:\Users\James\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
c:\Users\James\Anaconda\lib\site-packages\IPython\kernel\__main__.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

0       [is, this, hongkong, s, rodney, king, police, ...
1       [we, wont, move, and, im, ready, to, get, arre...
2       [rt, TWITTERHANDLE, footage, of, beating, prom...
3       [what, is, happening, in, hong, kong, is, some...
4       [fundinghongkong, travel, startup, TWITTERHAND...
5       [hk, police, use, pepper, spray, on, protester...
6       [rt, TWITTERHANDLE, footage, of, beating, prom...
7       [rt, TWITTERHANDLE, footage, of, beating, prom...
8       [squeezed, vscocam, vscohub, vscogang, vscogra...
9       [rt, TWITTERHANDLE, footage, of, beating, prom...
10      [breaking, hongkong, security, chief, says, 6,...
11      [trendingnews, hongkong, demonstranten, aangek...
12      [TWITTERHANDLE, in, hongkong, umbrellamovement...
13      [TWITTERHANDLE, in, hongkong, umbrellamovement...
14      [map, of, the, underpass, in, hongkong, where,...
15      [TWITTERHANDLE, in, hongkong, umbrellamovement...
16      [rt, TWITTERHANDLE, 37, men, and, 8, women, ar...
17                                 [hongkong, today, URL]
18      [rt, TWITTERHANDLE, icymi, hongkong, tensions,...
19      [rt, TWITTERHANDLE, footage, of, beating, prom...
20      [los, 7, goles, que, le, hicimos, a, hongkong,...
21      [exo, hongkong, fromlostplanet, 20140601, chan...
22      [TWITTERHANDLE, TWITTERHANDLE, this, was, how,...
23      [statement, by, hongkong, police, about, the, ...
24      [hongkong, oil, prices, URL, despite, pullback...
25      [hongkong, oil, prices, URL, despite, pullback...
26      [hongkong, oil, prices, URL, despite, pullback...
27      [hongkong, rt, TWITTERHANDLE, first, tear, gas...
28      [footage, of, beating, prompts, hongkong, poli...
29      [the, underpass, in, hongkong, where, police, ...
                              ...
1458    [rt, TWITTERHANDLE, the, grand, admiralty, hot...
1459    [rt, TWITTERHANDLE, yellow, umbrellas, against...
1460    [rt, TWITTERHANDLE, this, man, is, cheering, t...
1461    [rt, TWITTERHANDLE, 830, pm, hk, thousands, ra...
1462    [supervisortheyre, here, to, ensure, public, s...
1464    [rt, TWITTERHANDLE, mong, kok, 100, people, bu...
1465    [rt, TWITTERHANDLE, police, cant, stand, the, ...
1466    [rt, TWITTERHANDLE, legislator, leung, kwokhun...
1467    [rt, TWITTERHANDLE, audrey, eu, giving, out, f...
1468    [rt, TWITTERHANDLE, big, pictures, from, TWITT...
1469    [rt, TWITTERHANDLE, mong, kok, 100, people, bu...
1470    [rt, TWITTERHANDLE, earlier, the, 1, dollar, c...
1472    [mong, kok, 100, people, but, seems, barricade...
1474      [rt, TWITTERHANDLE, banner, now, occupyhk, URL]
1475    [rt, TWITTERHANDLE, TWITTERHANDLE, here, occup...
1476    [rt, TWITTERHANDLE, five, hk, press, unions, u...
1477    [rt, TWITTERHANDLE, 911pm, rodney, street, pac...
1478    [rt, TWITTERHANDLE, packed, around, the, stage...
1479              [rt, TWITTERHANDLE, now, occupyhk, URL]
1481    [rt, TWITTERHANDLE, this, is, the, post, start...
1482    [rt, TWITTERHANDLE, urgently, need, face, mask...
1484    [rt, TWITTERHANDLE, occupied, area, stretches,...
1485    [police, cant, stand, the, verbal, abuse, from...
1486    [rt, TWITTERHANDLE, barricades, also, building...
1487    [album, of, close, up, shots, of, the, pepper,...
1488    [rt, TWITTERHANDLE, calling, wooden, plates, h...
1490    [rt, TWITTERHANDLE, lung, wo, rd, what, source...
1491    [rt, TWITTERHANDLE, big, pictures, from, TWITT...
1492    [rt, TWITTERHANDLE, now, amp, signing, off, oc...
1493    [rt, TWITTERHANDLE, this, amount, of, people, ...
Name: tokens_w_stopwords, dtype: object

In [33]:
# pos_tag is a part of speech tagger, based on the text that it ingests.
# It needs some kind of sentence structure to work okay, so we'll use the tokens with stopwords.
# While its not built for twitter data, we can try it out and see how accurate it is
nltk.pos_tag
unique_tweets['pos'] = unique_tweets['tokens_w_stopwords'].apply(nltk.pos_tag)

# Printing out all words that come back as adjectives (JJ):
def find_all_adj(series):
    bag_of_words = [j[0] for j in series if j[1] == 'JJ']
    return bag_of_words if bag_of_words else []
    
adjectives = unique_tweets.pos.apply(find_all_adj)

final_list = []
for i in list(adjectives):
    final_list.extend(list(set(i)))

final_list = list(set(final_list))

c:\Users\James\Anaconda\lib\site-packages\IPython\kernel\__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [34]:
print final_list

['heutejournal', 'cute', 'malicious', 'excessive', 'chinese', 'global', 'displayed', 'yellow', 'kong', 'violent', 'own', 'asian', 'human', 'innovative', 'japan', 'hate', 'suisheng', '116th', 'le', 'police', 'jian', 'leung', 'much', 'hurtful', 'extra', 'young', 'only', 'rich', 'rabble', 'cardinal', 'te', 'worth', 'real', 'good', 'animal', 'big', 'stop', 'possible', 'finish', 'dark', 'joint', 'traffic', 'shameful', 'anonymous', 'international', 'front', 'viral', 'trouble', 'occupyhongkong', 'helpful', 'cable', 'tear', 'shy', 'unnecessary', 'large', 'bad', 'small', 'passionate', 'insane', 'r', 'financial', 'fair', 'tepid', 'national', 'easy', 'dead', 'breakthrough', 'likely', 'economic', '3nsailing', 'complete', 'agricultural', 'corrupt', 'close', 'sexual', 'special', 'outrageous', 'tungchung', 'symbiotic', 'beaten', 'legal', 'creative', 'current', 'outside', 'indian', 'various', 'new', 'adorable', 'public', '3d', 'available', 'pepper', 'full', 'christian', 'pathetic', 'wan', 'sixth', 'fugitive', 'free', 'huang', 'strong', 'soundcloud', 'jubilant', 'revolutionary', 'prodemocratic', 'great', 'bible', 'central', 'many', 'aguus', 'equal', 'urged', 'foreign', 'greatwall', 'protestorsoccupycentral', 'social', 'military', 'weird', 'whole', 'top', 'first', 'major', 'industrial', 'key', 'vid', 'civic', 'civil', 'sweet', 'irresponsible', 'powerful', 'arsenal', 'private', 'supporthongkong', 'lung', 'female', 'spanish', 'doubleedged', 'open', 'legislative', 'east', 'additive', 'silent', 'ophongkong', 'illegal', 'angry', 'live', 'handcuffed', 'long', 'next', 'few', 'genetic', 'occupycentral', 'crush', 'futile', 'basic', 'palestine', 'australian', '3dprinting', 'low', 'website', 'british', 'recipient', 'general', 'gear', 'successful', 'peaceful', 'hk', 'alive', 'icable', 'last', 'comfortable', 'true', 'former', 'tonight', 'main', 'dangerous', 'past', 'handicapped', 'sous', 'future', 'obvious', 'dirty', 'itinerary', 'fiveyear', 'property', 'average', 'ive', 'gratuitous', 'chaotic', 'pic', 'halloween', 'site', 'overzealous', 'sad', 'high', 'brutal', 'gordonmcqueen', 'ready', 'wonderful', 'david', 'occupied', 'id', 'physical', 'opportunityfinancial', 'hong', 'hongkong', 'mic', 'responsible', 'american', 'eric', 'hot', 'other', 'republic', 'fourth', 'automotive', 'widespread', 'several', 'poor', 'independent', 'apparent', 'normal', 'impartial', 'polite', 'evil', 'sigue', 'wrong', 'serious', 'hair', 'yuan', 'recent', 'early', 'natural', 'third', 'clear', 'proud', 'drive', 'concrete', 'verbal', 'detained', 'english', 'professional', 'democratic', 'unspeakable', 'western']

In [35]:
adjective_list = {
    'industrial': 0,
    'excessive': -1,
    'gratuitous': 1,
    'chaotic': -1,
    'national': 1,
    'young': 1,
    'yellow': 0,
    'high': 1,
    'middle': 0,
    'likely': 1,
    'economic': 0,
    'creative': 1,
    'open': 1,
    'physical': 0,
    'symbiotic': 1,
    'legal': 1,
    'next': 1,
    'genetic': 0,
    'angry': -1,
    'strong': 1,
    'peaceful': 1,
    'new': 1,
    'widespread': 1,
    'real': 1,
    'good': 1,
    'normal': 0,
    'successful': 1,
    'big': 1,
    'basic': -1,
    'hate': -1,
    'private': -1,
    'front': 0,
    'central': 0,
    'comfortable': 1,
    'last': 0,
    'helpful': 1,
    'third': 0,
    'many': 1,
    'clear': 1,
    'proud': 1,
    'brutal': -1,
    'large': 1,
    'dirty': -1,
    'professional': 1,
    'first': 0,
}

### Goal: Using the adjectives and some measure of sentiment, predict a given hashtag?

We'll need to build a couple more functions:

1. Let's write a function that creates a sentiment score for each tweet based on the adjectives above.

2. Set the targets of the model. We can do this two ways:

    1.One, using the hashtag column, which is what was generated based on the twitter search
    
    2.Create several target columns, based on the tweet itself, using a regex match for the hashtag.

3. Finally, build a logistic regressor using NLTK's sklearn implementation using our created sentiment as a regressor.

In [36]:
% matplotlib inline
import seaborn as sns

# First function: create a sentiment score column.
# Should take in a list of words, and return back the score as
# mean(sentiment_of_adjectives)
def measure_sentiment(words):


# Second function: Create a numeric target column.
def numeric_hashtag(tag):
    # we could use a dictionary similar to above to easily map hashtags to numeric values.
    targets = {
        u'hongkong': 0,
        u'occupycentral': 1,
        u'umbrellarevolution':2,
        u'china':3,
        u'hk':4,
        u'admiralty':5,
        u'occupyhk':6,
    }
    return targets[tag]

unique_tweets['sentiment'] = unique_tweets.tokens.apply(measure_sentiment)
print unique_tweets.sentiment.hist()

unique_tweets['target'] = unique_tweets.hashtag.apply(numeric_hashtag)

# Build a logistic regression using the sentiment feature and the numeric hashtags
from sklearn import linear_model as lm

lmfit = lm.LogisticRegression()
lmfit.fit(unique_tweets[['sentiment']], unique_tweets['target'])
print lmfit.score(unique_tweets[['sentiment']], unique_tweets['target'])

IndentationError: expected an indented block (<ipython-input-36-e7f1e4052762>, line 11)